<a href="https://colab.research.google.com/github/yewon91/mul_lectures/blob/main/NumPy_240103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy
 - 선형대수, 행렬, 수치연산과 관련된 라이브러리
 - 당연히 해야됨, 하지만 지금은 통계에 포커스

 - Numpy 기반으로 통계, 머신러닝 등 ==> 원리보다 응용, 결과 해석

In [ ]:
import numpy as np
print(np.__version__)

1.26.2


In [ ]:
import streamlit as st

print(st.__version__)

ModuleNotFoundError: No module named 'streamlit'

In [ ]:
num1 = [1,2,3,4]
num2 = [3,4,5,6]

num1+num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [ ]:
arr1 = np.array(num1)
arr2 = np.array(num2)
arr1

array([1, 2, 3, 4])

In [ ]:
arr2

array([3, 4, 5, 6])

In [ ]:
arr1 + arr2

array([ 4,  6,  8, 10])

In [ ]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
a1.dtype # Numpy int8, int16, int32, int64 => 메모리관리

dtype('int32')

In [ ]:
np.array([0.5,2,0.01,8]).dtype

dtype('float64')

## Numpy 배열 생성
- 1차원, 2차원, 3차원.. 배열 생성

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.arange(12).reshape(4, 1, 3)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [ ]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
b1 = np.arange(12).reshape(2, 2, 3)
b1.shape # 출력값은 tuple형태

(2, 2, 3)

In [ ]:
b2 = np.arange(5)
b2.shape

(5,)

In [ ]:
# 범위의 시작과 끝 정하기 배열 생성
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [ ]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## Numpy 기초문법 배우는 이유
- 문과생 : 데이터 분석가
- 이공계 : 수치연산, 배열, 수식을 활용해서 문제 풀이
  - 클래스, 딥러닝 클래스, NumPy 활용해서 딥러닝 알고리즘 적용, 클래스 & 라이브러리
  - 밑바닥부터 시작하는 딥러닝3

In [ ]:
# 단위행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr_I.shape

(3, 3)

In [ ]:
np.array(['1.5', '0.62']) # 데이터 형변환

array(['1,5', '0.62'], dtype='<U4')

In [ ]:
# astype() # pandas에서 사용가능
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr.dtype

dtype('float64')

In [ ]:
np.array(['1.5', '0.62'], dtype = float)

array([1.5 , 0.62])

In [ ]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)
num_f1

array([10, 21,  0,  4,  5])

In [ ]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(float)
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [ ]:
# 난수배열 생성

np.random.rand(2,3) # 0~1 사이의 실수 난수를 가짐

array([[0.90390627, 0.70336534, 0.00813792],
       [0.3606365 , 0.96840603, 0.70337024]])

In [ ]:
np.random.randint(2, 10, size=(3, 4))

array([[9, 7, 3, 7],
       [6, 9, 8, 3],
       [6, 4, 8, 4]])

In [ ]:
def generate_lotto_numbers():
    # 1부터 45까지의 숫자 중에서 6개를 무작위로 선택
    lotto_numbers = np.random.choice(range(1, 46), size=6, replace=False)

    # 선택된 숫자들을 정렬
    lotto_numbers.sort()

    return lotto_numbers

if __name__ == "__main__":
    # 로또 번호 생성 및 출력
    lotto_result = generate_lotto_numbers()
    print("로또 번호: ", lotto_result)

로또 번호:  [ 9 14 18 35 36 40]


In [ ]:
# 로또 번호 추첨기 만들어보기

# 조건1: 보너스숫자와 로또 메인 번호는 겹치지 않아야
# 조건2: 로또번호 내에서도 겹치는 숫자 없어야
# 조건3: 로또 번호(보너스 제외)는 오름차순으로 정렬되어야

lotto = np.random.randint(1, 46, size=(6, ))
bonus = np.random.randint(1, 46)
lotto = np.sort(lotto)   # 조건3

# way1
if bonus not in lotto:
    if np.unique(lotto).size == len(lotto):   # 2, 3, 3, 6, 10, 22 고유값 2, 3, 6, 10, 22
        print(f'이번 주 로또 당첨번호는 {lotto} + 보너스번호 {bonus}')

# way2
if bonus not in lotto:
    if np.unique(lotto).size == len(lotto):
        print(f'이번 주 로또 당첨번호는', end=' ')
        for i in range(6):
            print(lotto[i], end=' ')
            if i == 5:
                print(f'+ 보너스번호 ', bonus)

이번 주 로또 당첨번호는 [ 3  4  9 34 38 45] + 보너스번호 7
이번 주 로또 당첨번호는 3 4 9 34 38 45 + 보너스번호  7


In [ ]:
def lotto(n):  # n개를 받아드릴 함수
    numbers = []  # 로또 번호를 담아줄 빈 리스트 생성

    while len(numbers) < n:  # 횟수 n번을 반복해 줄 반복문
        num = np.random.randint(1, 45) # 랜덤한 숫자 뽑기
        if num not in numbers:  # 중복되는 숫자가 있는지 체크
            numbers.append(num) #없다면 리스트에 추가

    return numbers #반복구문을 완료한 리스트를 리턴

lotto(6)

[2, 20, 31, 33, 7, 42]

# 배열의 연산

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

# 비교연산

In [ ]:
arr1 > 20

array([False, False,  True,  True])

# 통계 연산
- 기술통계량 Descriptive statistics: 합,평균, 표준편차, 분산, 최소최대값, 누적합, 누적곱 메서드
- 현재 데이터 상태를 표현
- 통계 : 평균이 전부다! (Mean is Everything)
  + 모수 통계
  + 비모수 통계
  + 베이지안 통계

In [ ]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [ ]:
arr3.sum()

10

In [ ]:
arr3.mean()

2.0

In [ ]:
arr3.std()

1.4142135623730951

In [ ]:
arr3.var()
# 분산 - 각 변량이 평균에서 떨어진 정도의 평균
# 편차의 합이 항상 0이므로 편차의 제곱의 평균을 구한 것

# 편차의 합이 항상 0인지 확인
arr4 = np.random.randint(1,100,6)
print(arr4)
mean = arr4.mean()

ls = []
for i in arr4:
    ls.append(i-mean)

print(ls)

sum=0
for i in ls:
    sum += i

sum

[36  9 64 63 44 87]
[-14.5, -41.5, 13.5, 12.5, -6.5, 36.5]


0.0

# 누적곱
- cumsum() : 누적합
- cumprod() : 누적곱
- pandas에도 있음 (다 연결 돼있다)

In [ ]:
arr5 = np.arange(1,5)
arr5.cumsum()

array([ 1,  3,  6, 10])

In [ ]:
arr5.cumprod()

array([ 1,  2,  6, 24])

# 행렬연산
- 선형대수(Linear Algebra)를 위한 2차열 배열 연산도 지원 / 칸아카데미
- 행렬곱, 전치행렬, 역행렬, 행렬식

In [ ]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [ ]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [ ]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [ ]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [ ]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

# 배열의 인덱싱과 슬라이싱
- string, list, tuple과 동일한 방법으로 접근

In [ ]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
a1[4]

40

In [ ]:
# 50을 70으로 변경
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [ ]:
# 리스트 통해서 추출
a1[[0, 2, 4]]

idx_list = [0,2,4]
a1[idx_list]

array([ 0, 20, 40])

In [ ]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a2[0, 0]

10

In [ ]:
a2[2, 2]

90

In [ ]:
# 90을 95로 변경
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[1,2] = 43
a2

array([[10, 20, 30],
       [40, 50, 43],
       [70, 80, 95]])

In [ ]:
a2[0] = [1,2,3] # 좋은 코드 X
a2

array([[ 1,  2,  3],
       [40, 50, 43],
       [70, 80, 95]])

In [ ]:
a2[0] = np.array([4, 5, 6, 7])
a2

ValueError: could not broadcast input array from shape (4,) into shape (3,)

- 2차원 배열의 행과 열 위치 지정해서 원소 추출
  + (행의 위치1, 행의 위치2) / (열의 위치1, 열의 위치2)

In [ ]:
a2[[0, 2], [0, 1]]

array([ 4, 80])

In [ ]:
a2[0, 0], a2[2, 1]

(4, 80)

# 배열 조건문
 - pandas 문법과 유사

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
[a>3]

[array([False, False, False,  True,  True,  True])]

In [ ]:
a[a>3] # 조건식에 맞춰서 True값만 가져옴

array([4, 5, 6])

In [ ]:
a % 2 == 0

array([False,  True, False,  True, False,  True])

# 배열의 슬라이싱

In [ ]:
b1 = np.array([0, 1, 2, 3, 4, 5])
b1[1:4]

array([1, 2, 3])

In [ ]:
b1[:3]

array([0, 1, 2])

In [ ]:
b1[2:]

array([2, 3, 4, 5])

In [ ]:
b1[0:4:2]

array([0, 2])

In [ ]:
# 요소 변경
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0,  1, 25, 35, 45,  5])

In [ ]:
b1[3:6] = 60
b1

array([ 0,  1, 25, 60, 60, 60])

In [ ]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [ ]:
b2[1:, 1:]

array([[50, 60],
       [80, 90]])

In [ ]:
nums = [1, 2, 3, ['a', 'b']]
nums[3][0]

'a'

In [ ]:
b2[1][1:3]

array([50, 60])

# NumPy 조건문 (교재 없음)
- np.where : 단일 조건문
- np.select : 다중 조건문

- pandas에서도 사용가능

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#0, 1, 2, 3, 4, 50, 60, 70, 80, 90
np.where(arr < 5, arr, arr * 10)


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
# 100, 101, 2, 3, 4, 5, 12, 14, 16, 18
# 2 미만 +100
# 5 초과 x2

# 조건식과 대응되는 결과를 리스트로 만들기
cond_list = [arr > 5, arr < 2]
choice_list = [arr * 2, arr + 100]

np.select(cond_list, choice_list, default = arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## NumPy 수치연산 (저수준) 라이브러리
- 문과생 : NumPy의 수치연산 개념이 pandas, scipy, scikit-learn, tensorflow, pytorch에 영향을 주었다.
- 이공계 : 수치연산 알고리즘 구현하는 것을 기대, 각 연산의 종류 선형대수, 주요 메서드들에 좀 더 깊은 공부 필요